<h3>Search page</h3>
<a href="/">Главная</a>
<a href="/users">Пользователи</a>
<a href="/search">Поиск</a>
<br>
<br>
<br>
<?php foreach ($searchUsers as $name) : ?>
    <?php if (strpos($name, $term) !== false) : ?>
        <p> <?= $name ?></p>
    <?php endif; ?>
<?php endforeach; ?>

<br>
<br>
<br>
<p>User saerch: <?= htmlspecialchars($term) ?></p>
<br>
<br>
<br>
<form action="/search" method="get">
    <input type="search" required name="term" value="<?= htmlspecialchars($term) ?>">
    <input type="submit" value="Search">
</form>