<style>
    .wrap-form {
        display: flex;
        justify-content: center;
        align-items: center;

    }

    .user-form {
        width: 300px;
        margin: 100px 0 0 0;
        border: 1px solid red;
        border-radius: 25px;
        padding: 50px 25px;
    }

    label {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin: 0 0 20px;
    }

    .errors {
        color: red;
        font-weight: bold;
    }
</style>
<h3>Edit users page</h3>

<a href="/">Главная</a>

<?php
// echo "<pre>";
// print_r($editUser);
// echo "</pre>";
?>
<div class="wrap-form">
    <div class="user-form">
        <h3>Edit User</h3>
        <form action="/user/<?= htmlspecialchars($editUser['id']) ?>" method="post">
            <input type="hidden" name="_METHOD" value="PATCH">
            <div>
                <?php if (isset($errors['nickname'])) : ?>
                    <div class="errors"><?= $errors['nickname'] ?></div>
                <?php endif ?>
                <label>
                    Имя пользователя
                    <input type="text" name="editUser[nickname]" value="<?= htmlspecialchars($editUser['nickname'] ?? ''); ?>">
                </label>

            </div>
            <input type="submit" value="Update">
        </form>
    </div>
</div>