<h3>Edit users page</h3>

<a href="/">Главная</a>

<?php
echo "<pre>";
print_r($editUser);
echo "</pre>";
?>
<form action="/user/<?= htmlspecialchars($editUser['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
      <label>
          Название *
          <input type="text" name="editUser[nickname]" value="<?= htmlspecialchars($editUser['nickname'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['name'])): ?>
          <div><?= $errors['name'] ?></div>
      <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>