<h3>Users page</h3>
<?php
// echo "<pre>";
// print_r($users);
// echo "</pre>";
?>
<a href="/">Главная</a>
<a href="/users">Пользователи</a>
<a href="/search">Поиск</a>
<a href="/addusers/new">Регистрация</a>
<a href="/phpcourses/new">Добавить курс</a>
<a href="/test">test page</a>

<?php foreach ($users as ['id' => $id, 'firstName' => $firstName]) : ?>
    <p>id: <?= $id ?> firstName: <a href="/users/<?= $id ?>"><?= $firstName ?></a></p>
<?php endforeach; ?>