<h3>Users page</h3>
<?php
// echo "<pre>";
// print_r($users);
// echo "</pre>";
?>
<a href="/">Главная</a>
<a href="/users">Пользователи</a>
<a href="/search">Поиск</a>
<a href="/addusers/new">Регистрация</a>
<a href="/phpcourses/new">Добавить курс</a>
<a href="/test">test page</a>
<br>
<?php if(count($users) > 0): ?>

<?php foreach ($users as ['id' => $id, 'nickname' => $nickname]) : ?>
    <p>id: <?= htmlspecialchars($id) ?> nickname: <a href="/user/<?= htmlspecialchars($id) ?>"><?= htmlspecialchars($nickname) ?></a></p>
<?php endforeach; ?>

<?php else :?>

<p>Больше нет пользователей</p>

<?php endif; ?>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">previous</a>   <a href="?page=<?= $page + 1 ?>">next</a>