<h3><?= $nickname ?> user page</h3>
<?php
// echo "<pre>";
// print_r($users);
// echo "</pre>";
?>
<a href="/">Главная</a>
<a href="/users">Пользователи</a>
<a href="/search">Поиск</a>
<a href="/addusers/new">Регистрация</a>
<a href="/phpcourses/new">Добавить курс</a>
<a href="/test">test page</a>

<?php foreach ($users as $user) :

    if ($user['nickname'] == $nickname) : ?>

        <p>id: <?= $user['id'] ?>; nickname: <b><?= $user['nickname'] ?></b>; email: <b><?= $user['email'] ?></b>;</p>

    <?php endif; ?>

<?php endforeach; ?>